name: steadybit/definitions/kubernetes/deployments/policies/rolling-update
description: Challenges for redundancy during updates.
type: policy
tasks:
  - name: >-
      steadybit/definitions/kubernetes/deployments/experiments/faultless-redundancy-rolling-update
    version: 0.5.2
  - name: >-
      steadybit/definitions/kubernetes/deployments/weak-spots/deployment-strategy
    version: 0.5.2
    forEach:
      iterables:
        - container
      define:
        containerName: '{{container.name}}'
