name: steadybit/definitions/kubernetes/deployments/policies/recovery-pod
description: A service needs to be able to recover in case of problems. At a bare minimum, restarts need to be supported.
type: policy
tasks:
  - name: >-
      steadybit/definitions/kubernetes/deployments/experiments/recovery-of-single-container
    version: 0.5.2
    forEach:
      iterables:
        - container
      define:
        containerName: '{{container.name}}'
  - name: >-
      steadybit/definitions/kubernetes/deployments/experiments/recovery-of-single-host
    version: 0.5.2
