name: steadybit/definitions/kubernetes/deployments/policies/recovery-pod
description: >-
  A service needs to be able to recover in case of problems. At a bare minimum,
  it needs to support restarts when the container or underlying host has an
  outage.
shortDescription: At a bare minimum, your service needs to restart in case of an outage.
type: policy
tasks:
  - name: >-
      steadybit/definitions/kubernetes/deployments/experiments/recovery-of-single-container
    version: 0.5.6
    forEach:
      iterables:
        - container
      define:
        containerName: '{{container.name}}'
  - name: >-
      steadybit/definitions/kubernetes/deployments/experiments/recovery-of-single-host
    version: 0.5.6
