name: >-
  steadybit/definitions/kubernetes/deployments/policies/loose-coupling-on-startup
description: >-
  Nobody wants to ensure that services are started in a specific order. Verify
  that no startup coupling to dependent services would enforce a specific
  startup order.
shortDescription: Check for coupling to dependent services when restarting your service.
type: policy
tasks:
  - name: >-
      steadybit/definitions/kubernetes/deployments/experiments/loose-coupling-to-dependency-during-startup
    version: 0.5.4
    forEach:
      iterables:
        - dependency
      define:
        k8sDependencyClusterName: '{{dependency.mapping.kubernetes.cluster}}'
        k8sDependencyNamespaceName: '{{dependency.mapping.kubernetes.namespace}}'
        k8sDependencyDeploymentName: '{{dependency.mapping.kubernetes.deployment}}'
