name: steadybit/definitions/kubernetes/deployments/policies/redundancy-pod
description: Challenges for redundancy.
type: policy
tasks:
  - name: steadybit/definitions/kubernetes/deployments/experiments/faultless-redundancy-container
    version: 0.2.0
    forEach:
      iterables:
        - container
      define:
        containerName: '{{container.name}}'
  - name: steadybit/definitions/kubernetes/deployments/weak-spots/readiness-probe
    version: 0.2.0
    forEach:
      iterables:
        - container
      define:
        containerName: '{{container.name}}'
  - name: steadybit/definitions/kubernetes/deployments/weak-spots/single-replica
    version: 0.2.0
    forEach:
      iterables:
        - container
      define:
        containerName: '{{container.name}}'
