name: steadybit/definitions/kubernetes/deployments/policies/redundancy-pod
description: >-
  A single point of failure is hard to make resilient. Verify that your service
  is configured correctly for pod redundancy.
type: policy
tasks:
  - name: >-
      steadybit/definitions/kubernetes/deployments/experiments/faultless-redundancy-container
    version: 0.5.3
    forEach:
      iterables:
        - container
      define:
        containerName: '{{container.name}}'
  - name: steadybit/definitions/kubernetes/deployments/weak-spots/readiness-probe
    version: 0.5.3
    forEach:
      iterables:
        - container
      define:
        containerName: '{{container.name}}'
  - name: steadybit/definitions/kubernetes/deployments/weak-spots/single-replica
    version: 0.5.3
    forEach:
      iterables:
        - container
      define:
        containerName: '{{container.name}}'
