name: steadybit/definitions/kubernetes/deployments/policies/redundancy-host
description: Challenges for host redundancy.
type: policy
tasks:
  - name: >-
      steadybit/definitions/kubernetes/deployments/experiments/faultless-redundancy-host
    version: 0.4.0
  - name: steadybit/definitions/kubernetes/deployments/weak-spots/single-node
    version: 0.4.0
    forEach:
      iterables:
        - container
      define:
        containerName: '{{container.name}}'
