name: steadybit/definitions/kubernetes/deployments/policies/loose-coupling
description: >-
  Loose coupling to dependent services while processing requests is a dream come
  true. Check that your services can still respond successfully when
  dependencies are unavailable.
shortDescription: Test that your service functions when dependencies are unavailable.
type: policy
tasks:
  - name: >-
      steadybit/definitions/kubernetes/deployments/experiments/loose-coupling-to-dependency
    version: 0.5.4
    forEach:
      iterables:
        - dependency
      define:
        k8sDependencyClusterName: '{{dependency.mapping.kubernetes.cluster}}'
        k8sDependencyNamespaceName: '{{dependency.mapping.kubernetes.namespace}}'
        k8sDependencyDeploymentName: '{{dependency.mapping.kubernetes.deployment}}'
