name: Verify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: git remote add test git@github.com:steadybit/definitions.git
    - run: npx steadybit def-repo check
      env:
        STEADYBIT_TOKEN: ${{ secrets.STEADYBIT_TOKEN }}
        STEADYBIT_URL: https://platform-k8s.dev.steadybit.io
